version: "3.9"

services:
  ai:
    build: ./ai-service
    container_name: ai
    ports:
      - "8001:8001"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - ai
